backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "Dane przedszkola"
        name: "site"
        file: "data.json"
        fields:
          - { label: "Krótka nazwa (logo)", name: "shortName", widget: "string" }
          - { label: "Pełna nazwa szkoły", name: "schoolName", widget: "string" }
          - { label: "Telefon kontaktowy", name: "contactPhone", widget: "string" }
          - { label: "E-mail", name: "contactEmail", widget: "string" }
          - { label: "Historia", name: "aboutHistory", widget: "text" }
          - { label: "Dyrektor", name: "director", widget: "string" }
          - { label: "Zastępca dyrektora", name: "deputy", widget: "string" }
          - { label: "Godziny pracy", name: "hours", widget: "string" }
          - { label: "Wartości (każda w nowej linii)", name: "aboutValues", widget: "text" }
          - { label: "Link do Facebooka", name: "facebook", widget: "string" }