backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "ustawienia"
    label: "Ustawienia Strony"
    description: "Zarządzaj treścią na stronie głównej"
    files:
      - file: "data.json"
        label: "Główne Dane Strony"
        name: "dane"
        fields:
          - { label: "Pełna nazwa przedszkola", name: "schoolName", widget: "string" }
          - { label: "Krótka nazwa (w logo)", name: "shortName", widget: "string" }
          - { label: "Dyrektor", name: "director", widget: "string" }
          - { label: "Zastępca Dyrektora", name: "deputy", widget: "string" }
          - { label: "Godziny pracy", name: "hours", widget: "string" }
          - { label: "Historia", name: "aboutHistory", widget: "text" }
          - { label: "Wartości", name: "aboutValues", widget: "text" }
          - { label: "Telefon kontaktowy", name: "contactPhone", widget: "string" }
          - { label: "Adres e-mail", name: "contactEmail", widget: "string" }
          - { label: "Link do Facebooka", name: "facebook", widget: "string" }
